import { StatusBar } from 'expo-status-bar';
import { useEffect, useState } from 'react';
import { AppState, BackHandler, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import Constants from 'expo-constants';

import { createDummyAdapter } from './app/dummy/adapter';
import { createRealAdapter } from './app/real/adapter';
import { resolveClientConfig, localTenantBinding } from './app/real/config';
import { localTestTransport } from './app/real/transport';
import { scopedStorage } from './app/lib/auth/storage';
import { alternateTenant, tenant } from './app/dummy/fixtures';
import { bindFixture, clearPriorTenant, confirmSwitch, fixtureConnectionLink, initialBinding, requestSwitch } from './app/tenant/binding';
import { createFixtureQrScanner } from './app/tenant/scanner';
import { copy } from './app/ui/copy';
import { Button, FormInput, Notice, Section } from './app/ui/primitives';
import { paletteFor } from './app/ui/theme';

const clientConfig = resolveClientConfig(Constants.expoConfig?.extra || {});
const adapter = clientConfig.mode === 'real' ? createRealAdapter({ config: clientConfig, store: scopedStorage, transport: localTestTransport }) : createDummyAdapter();
const menuKeys = ['home', 'profile', 'dependents', 'registrations', 'discover', 'settings'];
const errorMessage = reason => reason?.message || 'Something went wrong. Please try again.';

export default function App() {
  const [startup, setStartup] = useState(true); const [signedIn, setSignedIn] = useState(false); const [screen, setScreen] = useState('home');
  const [locale, setLocale] = useState('zh-TW'); const [dark, setDark] = useState(false); const [binding, setBinding] = useState(initialBinding()); const [data, setData] = useState(adapter.snapshot());
  const [email, setEmail] = useState('member@example.test'); const [password, setPassword] = useState('templemate-demo'); const [signup, setSignup] = useState({ name: '', email: '', password: '' }); const [recoveryEmail, setRecoveryEmail] = useState('');
  const [profileName, setProfileName] = useState(data.profile.name); const [dependent, setDependent] = useState({ id: null, name: '', relationship: '家人' }); const [registration, setRegistration] = useState({ id: null, offering: '平安祈福', registrantName: data.profile.name });
  const [connectionLink, setConnectionLink] = useState(fixtureConnectionLink(tenant)); const [supportMessage, setSupportMessage] = useState(''); const [closureConfirmation, setClosureConfirmation] = useState(''); const [pending, setPending] = useState(false); const [error, setError] = useState(null); const [notice, setNotice] = useState(null);
  const t = copy[locale]; const palette = paletteFor(dark);

  useEffect(() => {
    const timer = setTimeout(() => setStartup(false), 180); const resume = AppState.addEventListener('change', value => { if (value === 'active') setNotice(null); });
    const back = BackHandler.addEventListener('hardwareBackPress', () => { if (screen !== 'home') { setScreen('home'); return true; } return false; });
    return () => { clearTimeout(timer); resume.remove(); back.remove(); };
  }, [screen]);
  const run = async action => { if (pending) return; setPending(true); setError(null); setNotice(null); try { const next = await action(); if (next) setData(next); setNotice(t.saved); } catch (reason) { setError(errorMessage(reason)); } finally { setPending(false); } };
  const signIn = () => run(async () => { const next = await adapter.signIn({ email, password }); setSignedIn(true); setBinding(clientConfig.mode === 'real' ? localTenantBinding(clientConfig) : bindFixture(fixtureConnectionLink(tenant))); return next; });
  const signOut = () => { Promise.resolve(adapter.logout?.()).catch(() => null); setSignedIn(false); setScreen('home'); setError(null); setNotice(null); };
  const reset = () => { if (adapter.kind !== 'dummy') { setError('Real mode does not reset account data.'); return; } const next = adapter.reset(); setData(next); setProfileName(next.profile.name); setDependent({ id: null, name: '', relationship: '家人' }); setRegistration({ id: null, offering: '平安祈福', registrantName: next.profile.name }); setBinding(initialBinding()); setNotice(t.saved); };
  const shared = { t, palette, locale, setLocale, dark, setDark, screen, setScreen, data, setData, binding, setBinding, connectionLink, setConnectionLink, profileName, setProfileName, dependent, setDependent, registration, setRegistration, supportMessage, setSupportMessage, closureConfirmation, setClosureConfirmation, pending, error, setError, notice, run, reset, signOut };
  if (startup) return <Shell palette={palette}><View style={styles.center}><Text style={[styles.brand, { color: palette.text }]}>{t.appName}</Text><Text style={[styles.muted, { color: palette.textMuted }]}>{t.loading}</Text></View></Shell>;
  if (!signedIn) return <SignedOut {...shared} {...{ email, setEmail, password, setPassword, signup, setSignup, recoveryEmail, setRecoveryEmail, signIn, setSignedIn }} />;
  return <Shell palette={palette}><Header t={t} palette={palette} binding={binding} onSignOut={signOut} /><Navigation {...shared} /><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Notice palette={palette} tone="info">{t.demo}</Notice>{error && <Notice palette={palette} tone="error">{error}<Button label={t.retry} palette={palette} tone="secondary" onPress={() => setError(null)} /></Notice>}{notice && <Notice palette={palette}>{notice}</Notice>}<AccountSurface {...shared} /></ScrollView></Shell>;
}

function Shell({ palette, children }) { return <SafeAreaProvider><SafeAreaView style={[styles.safe, { backgroundColor: palette.background }]}><StatusBar style={palette.statusBar} /><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.fill}>{children}</KeyboardAvoidingView></SafeAreaView></SafeAreaProvider>; }
function Header({ t, palette, binding, onSignOut }) { return <View style={[styles.header, { borderBottomColor: palette.border }]}><View style={styles.headerCopy}><Text style={[styles.brandSmall, { color: palette.text }]}>{t.appName}</Text><Text numberOfLines={1} style={[styles.muted, { color: palette.textMuted }]}>{binding.state === 'bound' ? `${t.connected} · ${binding.tenant.name}` : t.notConnected}</Text></View><Button label={t.signOut} palette={palette} tone="secondary" onPress={onSignOut} /></View>; }
function Navigation({ t, palette, screen, setScreen }) { return <View accessibilityRole="tablist" style={[styles.navigation, { borderBottomColor: palette.border }]}>{menuKeys.map(key => <Pressable accessibilityRole="tab" accessibilityState={{ selected: screen === key }} key={key} onPress={() => setScreen(key)} style={[styles.navItem, { borderColor: palette.border, backgroundColor: screen === key ? palette.primary : palette.inset }]}><Text numberOfLines={1} style={{ color: screen === key ? palette.onPrimary : palette.text, fontWeight: '800' }}>{t[key]}</Text></Pressable>)}</View>; }

function SignedOut({ t, palette, locale, setLocale, dark, setDark, screen, setScreen, email, setEmail, password, setPassword, signup, setSignup, recoveryEmail, setRecoveryEmail, pending, error, setError, notice, run, signIn, setSignedIn }) {
  const create = screen === 'signup'; const recovery = screen === 'recovery'; const signUp = () => run(async () => { const next = await adapter.signUp(signup); setSignedIn(true); return next; });
  return <Shell palette={palette}><ScrollView contentContainerStyle={styles.auth} keyboardShouldPersistTaps="handled"><Text style={[styles.brand, { color: palette.text }]}>{t.appName}</Text><Text style={[styles.lead, { color: palette.text }]}>{create ? t.createAccount : recovery ? t.forgotPassword : t.signInPrompt}</Text><Notice palette={palette} tone="info">{t.demo}</Notice>{!create && !recovery && <><Notice palette={palette} tone="info">{t.fixtureCredentials}</Notice><FormInput label={t.email} value={email} onChangeText={setEmail} autoCapitalize="none" palette={palette} /><FormInput label={t.password} value={password} onChangeText={setPassword} secureTextEntry autoCapitalize="none" palette={palette} /><Button label={pending ? '…' : t.signIn} palette={palette} onPress={signIn} disabled={pending} /><Button label={t.createAccount} palette={palette} tone="secondary" onPress={() => setScreen('signup')} /><Button label={t.forgotPassword} palette={palette} tone="secondary" onPress={() => setScreen('recovery')} /></>}{create && <><Notice palette={palette} tone="info">{t.signupNotice}</Notice><FormInput label={t.name} value={signup.name} onChangeText={name => setSignup({ ...signup, name })} palette={palette} /><FormInput label={t.email} value={signup.email} onChangeText={emailValue => setSignup({ ...signup, email: emailValue })} autoCapitalize="none" palette={palette} /><FormInput label={t.password} value={signup.password} onChangeText={passwordValue => setSignup({ ...signup, password: passwordValue })} secureTextEntry autoCapitalize="none" palette={palette} /><Button label={pending ? '…' : t.createAccount} palette={palette} onPress={signUp} disabled={pending} /><Button label={t.back} palette={palette} tone="secondary" onPress={() => setScreen('home')} /></>}{recovery && <><Notice palette={palette} tone="info">{t.recoveryNotice}</Notice><FormInput label={t.email} value={recoveryEmail} onChangeText={setRecoveryEmail} autoCapitalize="none" palette={palette} /><Button label={pending ? '…' : t.forgotPassword} palette={palette} onPress={() => run(() => adapter.recoverPassword({ email: recoveryEmail }))} disabled={pending} /><Button label={t.back} palette={palette} tone="secondary" onPress={() => setScreen('home')} /></>}{error && <Notice palette={palette} tone="error">{error}<Button label={t.retry} palette={palette} tone="secondary" onPress={() => setError(null)} /></Notice>}{notice && <Notice palette={palette}>{notice}</Notice>}<Preferences {...{ t, palette, locale, setLocale, dark, setDark }} /></ScrollView></Shell>;
}

function AccountSurface(props) {
  const { screen, t, palette, data, binding, setBinding, connectionLink, setConnectionLink, profileName, setProfileName, dependent, setDependent, registration, setRegistration, supportMessage, setSupportMessage, closureConfirmation, setClosureConfirmation, pending, setScreen, run, reset } = props;
  const bind = async source => { const next = source === 'qr' ? await createFixtureQrScanner(connectionLink).scanConnection() : bindFixture(connectionLink); setBinding(next); if (next.state === 'binding_failed') props.setError(t.bindingFailed); else props.setData(adapter.snapshot()); };
  if (screen === 'home') return <><Section title={t.account} palette={palette}><Text style={[styles.body, { color: palette.text }]}>{t.welcome}{data.profile.name}</Text><Text style={[styles.muted, { color: palette.textMuted }]}>{data.registrations.length} {t.registrations} · {data.dependents.length} {t.dependents}</Text></Section><Section title={t.templeConnection} palette={palette}><Text style={[styles.body, { color: palette.text }]}>{binding.state === 'bound' ? binding.tenant.name : t.notConnected}</Text>{binding.state !== 'bound' && binding.state !== 'switching' && <><FormInput label={t.connectionLink} value={connectionLink} onChangeText={setConnectionLink} autoCapitalize="none" palette={palette} /><Button label={t.connectWithLink} palette={palette} onPress={() => bind('link')} /><Button label={t.scanDemoCode} palette={palette} tone="secondary" onPress={() => bind('qr')} /></>}{binding.state === 'binding_failed' && <Notice palette={palette} tone="error">{t.bindingFailed}</Notice>}{binding.state === 'bound' && <Button label={t.switchTemple} palette={palette} tone="secondary" onPress={() => setBinding(requestSwitch(binding, fixtureConnectionLink(alternateTenant)))} />}{binding.state === 'switching' && <><Text style={[styles.body, { color: palette.text }]}>{t.switchDescription}</Text><Button label={t.confirmSwitch} palette={palette} onPress={() => { Promise.resolve(adapter.clearTenantState?.()).catch(() => null); setBinding(confirmSwitch(binding, clearPriorTenant(binding.tenant))); }} /></>}</Section><Section title={t.certificates} palette={palette}><Text style={[styles.body, { color: palette.text }]}>{t.certificateFixture}</Text></Section></>;
  if (screen === 'profile') return <Section title={t.profile} palette={palette}><FormInput label={t.name} value={profileName} onChangeText={setProfileName} palette={palette} /><Button label={t.save} palette={palette} disabled={pending} onPress={() => run(() => adapter.updateProfile({ name: profileName }))} /></Section>;
  if (screen === 'dependents') return <Section title={t.dependents} palette={palette}>{data.dependents.length === 0 && <Text style={[styles.muted, { color: palette.textMuted }]}>{t.emptyDependents}</Text>}{data.dependents.map(item => <ListCard key={item.id} palette={palette} title={`${item.name} · ${item.relationship}`} onPress={() => setDependent({ id: item.id, name: item.name, relationship: item.relationship })} />)}<FormInput label={t.name} value={dependent.name} onChangeText={name => setDependent({ ...dependent, name })} palette={palette} /><FormInput label={t.relationship} value={dependent.relationship} onChangeText={relationship => setDependent({ ...dependent, relationship })} palette={palette} /><Button label={dependent.id ? t.update : t.add} palette={palette} disabled={pending} onPress={() => run(() => dependent.id ? adapter.updateDependent(dependent.id, dependent) : adapter.createDependent(dependent)).then(() => setDependent({ id: null, name: '', relationship: '家人' }))} /><Button label={t.delete} palette={palette} tone="danger" disabled={!dependent.id || pending} onPress={() => run(() => adapter.deleteDependent(dependent.id)).then(() => setDependent({ id: null, name: '', relationship: '家人' }))} /></Section>;
  if (screen === 'registrations') return <Section title={t.registrations} palette={palette}>{data.registrations.length === 0 && <Text style={[styles.muted, { color: palette.textMuted }]}>{t.emptyRegistrations}</Text>}{data.registrations.map(item => <ListCard key={item.id} palette={palette} title={`${item.offering} · ${item.registrantName}`} caption={item.readOnly ? t.paidReadOnly : item.state === 'draft' ? t.draft : item.state} disabled={item.readOnly} onPress={() => !item.readOnly && setRegistration({ id: item.id, offering: item.offering, registrantName: item.registrantName })} />)}<FormInput label={t.offering} value={registration.offering} onChangeText={offering => setRegistration({ ...registration, offering })} palette={palette} /><FormInput label={t.registrant} value={registration.registrantName} onChangeText={registrantName => setRegistration({ ...registration, registrantName })} palette={palette} /><Button label={registration.id ? t.update : t.add} palette={palette} disabled={pending} onPress={() => run(() => registration.id ? adapter.updateRegistration(registration.id, registration) : adapter.createRegistration(registration)).then(() => setRegistration({ id: null, offering: '平安祈福', registrantName: data.profile.name }))} /></Section>;
  if (screen === 'discover') return <><DataSection title={t.activity} items={data.events} palette={palette} /><DataSection title={t.services} items={data.services} palette={palette} /><DataSection title={t.gallery} items={data.gallery} palette={palette} /></>;
  if (screen === 'settings') return <Section title={t.settings} palette={palette}><Preferences {...props} /><Text style={[styles.subhead, { color: palette.text }]}>{t.privacyHelp}</Text><Button label={t.needHelp} palette={palette} tone="secondary" onPress={() => setScreen('assistance')} /><Button label={t.contactTemple} palette={palette} tone="secondary" onPress={() => setScreen('contact')} /><Button label={t.privacyRequest} palette={palette} tone="secondary" onPress={() => setScreen('privacy')} /><Button label={t.closeAccount} palette={palette} tone="danger" onPress={() => setScreen('closure')} />{adapter.kind === 'dummy' && <Button label={t.resetDemo} palette={palette} tone="secondary" onPress={reset} />}</Section>;
  if (screen === 'assistance' || screen === 'contact') { const isHelp = screen === 'assistance'; return <Section title={isHelp ? t.needHelp : t.contactTemple} palette={palette}><FormInput label={t.message} value={supportMessage} onChangeText={setSupportMessage} palette={palette} /><Button label={t.send} palette={palette} onPress={() => run(() => isHelp ? adapter.submitAssistance({ message: supportMessage }) : adapter.contactTemple({ message: supportMessage })).then(() => setScreen('settings'))} /><Button label={t.back} palette={palette} tone="secondary" onPress={() => setScreen('settings')} /></Section>; }
  if (screen === 'privacy') return <Section title={t.privacyRequest} palette={palette}><Button label={t.exportData} palette={palette} onPress={() => run(() => adapter.requestPrivacy({ kind: 'export' }))} /><Button label={t.deletionRequest} palette={palette} tone="danger" onPress={() => run(() => adapter.requestPrivacy({ kind: 'deletion' }))} /><Button label={t.back} palette={palette} tone="secondary" onPress={() => setScreen('settings')} /></Section>;
  return <Section title={t.closeAccount} palette={palette}><Text style={[styles.body, { color: palette.text }]}>{t.closeDescription}</Text><FormInput label="CLOSE" value={closureConfirmation} onChangeText={setClosureConfirmation} autoCapitalize="characters" palette={palette} /><Button label={t.closeAccount} palette={palette} tone="danger" onPress={() => run(() => adapter.closeAccount({ confirmation: closureConfirmation })).then(props.signOut)} /><Button label={t.back} palette={palette} tone="secondary" onPress={() => setScreen('settings')} /></Section>;
}

function Preferences({ t, palette, locale, setLocale, dark, setDark }) { return <View style={styles.preferences}><Text style={[styles.label, { color: palette.text }]}>{t.language}</Text><View style={styles.choiceRow}><Button label="繁中" palette={palette} tone="secondary" onPress={() => setLocale('zh-TW')} /><Button label="English" palette={palette} tone="secondary" onPress={() => setLocale('en')} /></View><Text style={[styles.label, { color: palette.text }]}>{t.appearance}</Text><Button label={dark ? t.light : t.dark} palette={palette} tone="secondary" onPress={() => setDark(value => !value)} /></View>; }
function ListCard({ palette, title, caption, onPress, disabled }) { return <Pressable accessibilityRole="button" accessibilityState={{ disabled: Boolean(disabled) }} disabled={disabled} onPress={onPress} style={[styles.listCard, { backgroundColor: palette.inset, borderColor: palette.border }, disabled && styles.disabled]}><Text style={[styles.body, { color: palette.text }]}>{title}</Text>{caption && <Text style={[styles.muted, { color: palette.textMuted }]}>{caption}</Text>}</Pressable>; }
function DataSection({ title, items, palette }) { return <Section title={title} palette={palette}>{items.map(item => <Text key={item.id} style={[styles.body, { color: palette.text }]}>{item.title}{item.date ? ` · ${item.date}` : ''}</Text>)}</Section>; }

const styles = StyleSheet.create({ safe: { flex: 1 }, fill: { flex: 1 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10, padding: 24 }, auth: { padding: 24, gap: 14, flexGrow: 1, justifyContent: 'center' }, header: { minHeight: 78, paddingHorizontal: 18, paddingVertical: 12, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 }, headerCopy: { flex: 1 }, brand: { fontSize: 34, fontWeight: '900', letterSpacing: -0.6 }, brandSmall: { fontSize: 22, fontWeight: '900' }, lead: { fontSize: 17, fontWeight: '700' }, muted: { fontSize: 14, lineHeight: 20 }, body: { fontSize: 16, lineHeight: 23 }, label: { fontSize: 14, fontWeight: '800' }, subhead: { fontSize: 16, fontWeight: '800', marginTop: 4 }, navigation: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingHorizontal: 14, paddingVertical: 12, borderBottomWidth: 1 }, navItem: { minHeight: 40, paddingHorizontal: 12, justifyContent: 'center', borderRadius: 20, borderWidth: 1 }, content: { padding: 16, gap: 14, paddingBottom: 32 }, listCard: { padding: 13, gap: 4, borderWidth: 1, borderRadius: 12 }, choiceRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' }, preferences: { gap: 9 }, disabled: { opacity: 0.52 } });
