export const copy = {
  'zh-TW': {
    appName: 'TempleMate', demo: '示範模式：資料只保留在此裝置可重設的範圍內，且不會連線至服務。', loading: '正在準備示範帳戶…',
    signIn: '登入', signOut: '登出', signInPrompt: '以示範帳戶登入', email: '電子郵件', password: '密碼', name: '姓名', relationship: '關係',
    home: '首頁', profile: '個人資料', dependents: '家屬', registrations: '登記', discover: '探索', settings: '設定', save: '儲存', add: '新增', update: '更新', delete: '刪除', retry: '再試一次', back: '返回',
    createAccount: '建立帳號', forgotPassword: '忘記密碼', fixtureCredentials: '示範帳號：member@example.test　密碼：templemate-demo', recoveryNotice: '此示範不會寄送電子郵件。', signupNotice: '帳號建立將在未來安全帳戶服務啟用後提供。',
    account: '帳戶', templeConnection: '宮廟連結', connected: '已連結', notConnected: '尚未連結', connectionLink: 'TempleMate 連結', connectWithLink: '使用連結連結', scanDemoCode: '掃描示範 QR', switchTemple: '切換宮廟', switchDescription: '確認後會清除先前宮廟的登入、快取與待處理示範資料。', confirmSwitch: '確認並切換',
    certificates: '證明文件', certificateFixture: '平安祈福參與證明（示範）', appearance: '外觀', language: '語言', light: '淺色', dark: '深色', privacyHelp: '隱私與協助', needHelp: '需要協助', contactTemple: '聯絡宮廟', privacyRequest: '隱私請求', exportData: '匯出資料', deletionRequest: '刪除請求', closeAccount: '關閉帳戶', closeDescription: '輸入 CLOSE 以確認示範帳戶關閉。', resetDemo: '重設示範資料', message: '訊息', send: '送出', offering: '項目', offeringSlug: '項目識別碼', registrant: '登記人', draft: '草稿', paidReadOnly: '已完成（僅供展示，不能修改）', saved: '已儲存', welcome: '您好，', activity: '活動', services: '服務', gallery: '相簿', emptyDependents: '尚未加入家屬。', emptyRegistrations: '尚未建立登記。', emptyCertificates: '尚無證明文件。', emptyCollection: '目前沒有資料。', collectionFailed: '資料載入失敗，請稍後再試。', notFound: '找不到頁面', notFoundDescription: '此頁面無法使用，已安全保留您的帳戶資料。', bindingFailed: '連結失敗，請檢查示範連結後再試一次。'
  },
  en: {
    appName: 'TempleMate', demo: 'Demo mode: data stays within this resettable device scope and never contacts a service.', loading: 'Preparing the demo account…',
    signIn: 'Sign in', signOut: 'Sign out', signInPrompt: 'Sign in with the demo account', email: 'Email', password: 'Password', name: 'Name', relationship: 'Relationship',
    home: 'Home', profile: 'Profile', dependents: 'Dependents', registrations: 'Registrations', discover: 'Explore', settings: 'Settings', save: 'Save', add: 'Add', update: 'Update', delete: 'Delete', retry: 'Try again', back: 'Back',
    createAccount: 'Create account', forgotPassword: 'Forgot password', fixtureCredentials: 'Demo account: member@example.test  Password: templemate-demo', recoveryNotice: 'This demo does not send email.', signupNotice: 'Account creation will be available with a future secure account service.',
    account: 'Account', templeConnection: 'Temple connection', connected: 'Connected', notConnected: 'Not connected', connectionLink: 'TempleMate connection link', connectWithLink: 'Connect with link', scanDemoCode: 'Scan demo QR', switchTemple: 'Switch temple', switchDescription: 'Confirmation clears the previous temple’s sign-in, cache, and pending demo data.', confirmSwitch: 'Confirm switch',
    certificates: 'Certificates', certificateFixture: 'Peace blessing participation certificate (demo)', appearance: 'Appearance', language: 'Language', light: 'Light', dark: 'Dark', privacyHelp: 'Privacy & help', needHelp: 'Need help', contactTemple: 'Contact temple', privacyRequest: 'Privacy request', exportData: 'Export data', deletionRequest: 'Deletion request', closeAccount: 'Close account', closeDescription: 'Enter CLOSE to confirm closing this demo account.', resetDemo: 'Reset demo data', message: 'Message', send: 'Send', offering: 'Offering', offeringSlug: 'Offering identifier', registrant: 'Registrant', draft: 'Draft', paidReadOnly: 'Completed (display only; cannot be edited)', saved: 'Saved', welcome: 'Hello, ', activity: 'Events', services: 'Services', gallery: 'Gallery', emptyDependents: 'No dependents yet.', emptyRegistrations: 'No registrations yet.', emptyCertificates: 'No certificates yet.', emptyCollection: 'No records yet.', collectionFailed: 'Unable to load account records. Try again later.', notFound: 'Page unavailable', notFoundDescription: 'This page is unavailable; your account data remains safe.', bindingFailed: 'Connection failed. Check the demo link and try again.'
  }
};
